"""updated fllows table

Revision ID: c3eff3963cf4
Revises: a4658c90e5b8
Create Date: 2021-08-16 11:07:00.906367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3eff3963cf4'
down_revision = 'a4658c90e5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follows', 'id')
    # ### end Alembic commands ###
