"""newMigration

Revision ID: a4658c90e5b8
Revises: 432b9dfc041a
Create Date: 2021-08-16 10:08:32.964427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4658c90e5b8'
down_revision = '432b9dfc041a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('user_id_follow_owner', sa.Integer(), nullable=True),
    sa.Column('user_id_follower', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_follow_owner'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_follower'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
