"""empty message

Revision ID: 942deb94e405
Revises: d892d839ee24
Create Date: 2021-09-26 22:00:53.925626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942deb94e405'
down_revision = 'd892d839ee24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipes_name_key', 'recipes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('recipes_name_key', 'recipes', ['name'])
    # ### end Alembic commands ###
